### ISSUE TITLE
Delphi 7

### ISSUE THREAD

**Issue by Rusland3000** [ekot1/DelphiSVG#14]
Is it possible install on Delphi 7?

**Comment by ekot1** [comment]
I don't have Delphi 7 to try, but I think no.

**Comment by eugeneilyin** [comment]
@Rusland3000, no you cann't compile it under Delphi 7, because the library depends on `DirectDraw`, `GDIPAPI`, `GDIPOBJ`, `GDIPUTIL`, `Math.Vectors`, and `Xml.XmlIntf` units. These units could be compiled under Delphi 7 if you find the sources and remove unit prefixes in the uses sections of each unit respectively.

But the main issue is the [`NetEncoding`](https://github.com/ekot1/DelphiSVG/blob/9bb2d1e7abd997bedd38f4c829d8171b52446a34/svg/SVG.pas#L34) unit.
The `TNetEncoding` class uses `class var` Delphi feature which is not available under Delphi 7.
